## Numpy and Pandas

In [1]:
# we need both mupy and pandas
import numpy as np
import pandas as pd

In [5]:
# Numpy includes an array data type
a = np.array([1,2,3,4,5])
a*8
b = np.array([8,7,6,5,4])
b*a

array([ 8, 14, 18, 20, 20])

In [160]:
# Stats
# np.random.seed(42)
c = np.random.normal(5,2) # mean of 5 sd of 2
c

5.1350564093758475

In [168]:
costs = np.random.normal(5, 2, 100) ## mean=5 sd=2 100 items
costs

array([ 5.82759819,  4.62942468,  4.7403586 ,  5.08762294,  4.705996  ,
        6.92775823,  9.421046  ,  3.88501643,  2.26039404,  4.8234359 ,
       10.15941868,  3.39265086,  8.27823361,  8.35540163,  3.89282352,
        6.13796616,  8.25679325,  4.24174452,  4.59283928,  3.83663817,
        2.97048654,  3.70144491,  2.55211947,  5.06816694,  3.46005354,
        5.46757182,  1.88820871,  5.66176046,  6.66705792,  1.01252871,
        5.74811314,  7.45533798,  2.58071796,  8.34514477,  5.83803802,
        3.58997629,  4.88846184,  6.11665383,  5.15201078,  6.07751198,
        3.15865281,  5.33872165,  2.17257101,  4.77754788,  3.19218472,
        3.52894011,  7.47218635,  7.18262024,  6.21827624,  2.81537447,
        4.3671831 ,  7.4261954 ,  5.28343383,  9.63865908,  5.78663568,
        5.38409823,  4.38176707,  5.26708181,  4.69506033,  6.41621735,
        6.91340463,  3.42802108,  2.33753409,  1.32758925,  6.01598265,
        2.79326679,  0.69421881,  5.77715721,  9.98599903,  4.98785818,
        6.67698155,  5.16365872,  4.80222069,  6.83815297,  4.41945091,
        5.53478463,  5.64339561,  3.66381909,  6.9840847 ,  4.65008049,
        3.48850968,  6.07301969,  3.20306404,  5.05636231,  4.98176201,
        7.17179113,  5.94939647,  4.94994608,  6.6355326 ,  7.7804151 ,
        6.11562061,  5.02070524,  2.37632754,  2.86977267,  4.38955059,
        3.7809756 ,  4.62605739,  5.11329985,  6.05938551,  4.85900244])

In [179]:
# stats
costs.mean()
print(costs.max())
costs.min()
costs.std()
costs.sum()
## only the very last operation is shown in jupyter output

10.159418675308636

np.float64(511.33609132932605)

In [186]:
# formatting printed output
print( f'Mean: {costs.mean():0.3f} min:{costs.min()}'  )

Mean: 5.113 min:0.6942188140950343

In [239]:
# reading in external data
# NB this may be a local file or a file on a network
# sp500 = pd.read_csv('StockData/SP500.csv')
sp500= pd.read_csv('https://raw.githubusercontent.com/onionmccabbage/pythonOneSept2026/refs/heads/main/StockData/SP500.csv')
sp500

,Date,Open,High,Low,Close,Adj Close,Volume
0,9/30/13,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,10/01/13,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,10/02/13,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,10/03/13,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,10/04/13,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...,...
1255,9/24/18,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
1256,9/25/18,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
1257,9/26/18,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
1258,9/27/18,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
1259,9/28/18,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [240]:
# sp500.info()
# we often need to convert a string into a date
sp500['Date'] = pd.to_datetime( sp500['Date'], format='%m/%d/%y' ) # we specify the current format
sp500

,Date,Open,High,Low,Close,Adj Close,Volume
0,2013-09-30,1687.260010,1687.260010,1674.989990,1681.550049,1681.550049,3308630000
1,2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2,2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
3,2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
4,2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
...,...,...,...,...,...,...,...
1255,2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
1256,2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
1257,2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
1258,2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
1259,2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000

In [241]:
# We can use any column to be an index
sp500.set_index(['Date'], inplace=True)

In [247]:
# slicing
sp500.loc['2013-10'] # locate all index members (dates) for 2013

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2013-10-01,1682.410034,1696.550049,1682.069946,1695.000000,1695.000000,3238690000
2013-10-02,1691.900024,1693.869995,1680.339966,1693.869995,1693.869995,3148600000
2013-10-03,1692.349976,1692.349976,1670.359985,1678.660034,1678.660034,3279650000
2013-10-04,1678.790039,1691.939941,1677.329956,1690.500000,1690.500000,2880270000
2013-10-07,1687.150024,1687.150024,1674.699951,1676.119995,1676.119995,2678490000
2013-10-08,1676.219971,1676.790039,1655.030029,1655.449951,1655.449951,3569230000
2013-10-09,1656.989990,1662.469971,1646.469971,1656.400024,1656.400024,3577840000
2013-10-10,1660.880005,1692.560059,1660.880005,1692.560059,1692.560059,3362300000
2013-10-11,1691.089966,1703.439941,1688.520020,1703.199951,1703.199951,2944670000
2013-10-14,1699.859985,1711.030029,1692.130005,1710.140015,1710.140015,2580580000
2013-10-15,1709.170044,1711.569946,1695.930054,1698.060059,1698.060059,3327740000
2013-10-16,1700.489990,1721.760010,1700.489990,1721.540039,1721.540039,3486180000
2013-10-17,1720.170044,1733.449951,1714.119995,1733.150024,1733.150024,3453590000
2013-10-18,1736.719971,1745.310059,1735.739990,1744.500000,1744.500000,3664890000
2013-10-21,1745.199951,1747.790039,1740.670044,1744.660034,1744.660034,3052710000
2013-10-22,1746.479980,1759.329956,1746.479980,1754.670044,1754.670044,3850840000
2013-10-23,1752.270020,1752.270020,1740.500000,1746.380005,1746.380005,3713380000
2013-10-24,1747.479980,1753.939941,1745.500000,1752.069946,1752.069946,3671700000
2013-10-25,1756.010010,1759.819946,1752.449951,1759.770020,1759.770020,3175720000
2013-10-28,1759.420044,1764.989990,1757.670044,1762.109985,1762.109985,3282300000
2013-10-29,1762.930054,1772.089966,1762.930054,1771.949951,1771.949951,3358460000
2013-10-30,1772.270020,1775.219971,1757.239990,1763.310059,1763.310059,3523040000
2013-10-31,1763.239990,1768.530029,1755.719971,1756.540039,1756.540039,3826530000